"""baseline schema

Revision ID: 53b7e33debd0
Revises: 
Create Date: 2026-07-14 21:08:17.617350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53b7e33debd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('columnlayout',
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('columns_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('fxrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fxrate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fxrate_date'), ['date'], unique=True)

    op.create_table('pluginconfig',
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('plugin_id')
    )
    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tagoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tagoption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tagoption_field'), ['field'], unique=False)
        batch_op.create_index('ix_tagoption_field_value', ['field', 'value'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('miscexpense',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jpy_override', sa.Integer(), nullable=True),
    sa.Column('override_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jpy_auto', sa.Integer(), nullable=True),
    sa.Column('jpy_settled', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('miscexpense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miscexpense_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_miscexpense_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_miscexpense_source'), ['source'], unique=False)

    op.create_table('shipmentorder',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jpy_override', sa.Integer(), nullable=True),
    sa.Column('override_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jpy_auto', sa.Integer(), nullable=True),
    sa.Column('jpy_settled', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('intl_tracking_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('special_fee_jpy', sa.Integer(), nullable=True),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipmentorder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipmentorder_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipmentorder_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_shipmentorder_shipment_no_active', ['shipment_no'], unique=True, sqlite_where=sa.text('shipment_no IS NOT NULL AND deleted_at IS NULL'))
        batch_op.create_index(batch_op.f('ix_shipmentorder_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipmentorder_status'), ['status'], unique=False)

    op.create_table('taobaoorder',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('price_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jpy_override', sa.Integer(), nullable=True),
    sa.Column('override_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jpy_auto', sa.Integer(), nullable=True),
    sa.Column('jpy_settled', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('express_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('express_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('taobao_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shipment_order_id'], ['shipmentorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taobaoorder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taobaoorder_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_taobaoorder_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_taobaoorder_express_no'), ['express_no'], unique=False)
        batch_op.create_index('ix_taobaoorder_order_no_active', ['order_no'], unique=True, sqlite_where=sa.text('order_no IS NOT NULL AND deleted_at IS NULL'))
        batch_op.create_index(batch_op.f('ix_taobaoorder_shipment_order_id'), ['shipment_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taobaoorder_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_taobaoorder_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_taobaoorder_taobao_account'), ['taobao_account'], unique=False)

    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taobao_order_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taobao_order_id'], ['taobaoorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orderitem_taobao_order_id'), ['taobao_order_id'], unique=False)

    op.create_table('taobaostaging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('taobao_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('express_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imported_taobao_order_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_taobao_order_id'], ['taobaoorder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taobaostaging', schema=None) as batch_op:
        batch_op.create_index('ix_staging_order_no', ['order_no'], unique=True, sqlite_where=sa.text('order_no IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_taobaostaging_status'), ['status'], unique=False)

    op.create_table('stagingitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staging_id'], ['taobaostaging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stagingitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stagingitem_staging_id'), ['staging_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stagingitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stagingitem_staging_id'))

    op.drop_table('stagingitem')
    with op.batch_alter_table('taobaostaging', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taobaostaging_status'))
        batch_op.drop_index('ix_staging_order_no', sqlite_where=sa.text('order_no IS NOT NULL'))

    op.drop_table('taobaostaging')
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orderitem_taobao_order_id'))

    op.drop_table('orderitem')
    with op.batch_alter_table('taobaoorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taobaoorder_taobao_account'))
        batch_op.drop_index(batch_op.f('ix_taobaoorder_status'))
        batch_op.drop_index(batch_op.f('ix_taobaoorder_source'))
        batch_op.drop_index(batch_op.f('ix_taobaoorder_shipment_order_id'))
        batch_op.drop_index('ix_taobaoorder_order_no_active', sqlite_where=sa.text('order_no IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_taobaoorder_express_no'))
        batch_op.drop_index(batch_op.f('ix_taobaoorder_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_taobaoorder_date'))

    op.drop_table('taobaoorder')
    with op.batch_alter_table('shipmentorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipmentorder_status'))
        batch_op.drop_index(batch_op.f('ix_shipmentorder_source'))
        batch_op.drop_index('ix_shipmentorder_shipment_no_active', sqlite_where=sa.text('shipment_no IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_shipmentorder_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_shipmentorder_date'))

    op.drop_table('shipmentorder')
    with op.batch_alter_table('miscexpense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miscexpense_source'))
        batch_op.drop_index(batch_op.f('ix_miscexpense_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_miscexpense_date'))

    op.drop_table('miscexpense')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('tagoption', schema=None) as batch_op:
        batch_op.drop_index('ix_tagoption_field_value')
        batch_op.drop_index(batch_op.f('ix_tagoption_field'))

    op.drop_table('tagoption')
    op.drop_table('setting')
    op.drop_table('pluginconfig')
    with op.batch_alter_table('fxrate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fxrate_date'))

    op.drop_table('fxrate')
    op.drop_table('columnlayout')
    # ### end Alembic commands ###
